version: '3.8'

services:
  third-service:
    build:
      context: ./third-service
      dockerfile: docker/Dockerfile
    container_name: third-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  second-service:
    build:
      context: ./second-service
      dockerfile: docker/Dockerfile
    container_name: second-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - third-service

  first-service:
    build:
      context: ./first-service
      dockerfile: docker/Dockerfile
    container_name: first-service
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  client-service:
    build:
      context: ./client-service
      dockerfile: docker/Dockerfile
    container_name: client-service
    ports:
      - "8088:8088"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - first-service
      - second-service
      - third-service

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - microservices-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:
  microservices-network:
    driver: bridge 