server:
  port: 8099
  servlet:
    context-path: /

spring:
  application:
    name: client-service
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: "*"